### ISSUE TITLE
Cheapest availability zone incorrect

### ISSUE THREAD

**Issue by rasathus** [arithmetric/awespottr#5]
Thanks for such a timesaving tool.  Being able to find prices across a number of regions is rather useful.  However I did notice that its suggestions on the cheapest zone seem to be incorrect, as per the output below ... 

```
~/Downloads  awespottr p3.8xlarge
Checking spot prices for p3.8xlarge instance type.

AWS Zone                 Hourly Rate 
------------------------ ------------
us-west-2b               $3.672000   
us-west-2c               $3.672000   
us-east-1f               $3.728000   
us-east-1b               $3.736400   
us-east-1a               $3.782400   
eu-west-1a               $3.966000   
eu-west-1c               $3.966000   
us-east-2b               $5.262000   
us-east-2a               $5.519800   
ap-northeast-2a          $19.924000  
ap-northeast-2c          $19.924000  
ap-northeast-1a          $20.972000  
ap-northeast-1c          $20.972000  

Cheapest hourly rate for p3.8xlarge is $19.924000 in zone ap-northeast-2c
```

In this case I would have expected it to flag us-west-2b and us-west-2c as the cheapest zones.

**Comment by arithmetric** [comment]
@rasathus Thanks for the report. This is now fixed in v0.3.0.

The logic for finding the cheapest rate was doing a text comparison on the prices, so "10" was sorted before "3". This problem was less obvious with prices lower than 1.
